Repository fga-eps-mds/2019.2-Acacia-Frontend, pull requests merged in 2019-11, with the labels that each got.

#24 124 relationship heroku actions
  .github/workflows/cd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  package.json
  src/views/HomePage.vue
  staging-server.js
Labels: devops

#18 #79 Configurar ambiente de homologação
  Dockerfile
  src/views/HomePage.vue
  staging-server.js
Labels: devops

#29 Release/v0.2.0
  .babelrc
  .env.development
  .env.staging
  .eslintrc.js
  .github/workflows/cd.yml
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/assets/images/cellFront.svg
  src/assets/images/cellShadow.svg
  src/assets/logo.svg
  src/assets/stylesheets/colors.scss
  src/components/input/DatePicker.vue
  src/components/input/GenericButton.vue
  src/components/input/ImageUpload.vue
  src/components/input/RegisterButton.vue
  src/components/input/SelectField.vue
  src/components/input/SignButton.vue
  src/components/input/StringList.vue
  src/components/input/TextField.vue
  src/components/layout/BottomBar.vue
  src/components/layout/Card.vue
  src/components/layout/SideBar.vue
  src/components/layout/TopBar.vue
  src/components/layout/TopBarBeta.vue
  src/components/layout/Upload.vue
  src/components/layout/WeeklyCard.vue
  src/components/visualization/HarvestDigest.vue
  src/config.js
  src/main.js
  src/plugins/i18n.js
  src/plugins/vuetify.js
  src/router.js
  src/store.js
  src/views/CalendarPage.vue
  src/views/Dashboard.vue
  src/views/HarvestRegistration.vue
  src/views/HomePage.vue
  src/views/LandingPage.vue
  src/views/PropertyRegistration.vue
  src/views/Signin.vue
  src/views/Signup.vue
  src/views/TreeRegistration.vue
  staging-server.js
  tests/unit/components.spec.js
  tests/unit/signin.spec.js
  tests/views/harvest_registration.spec.js
  vue.config.js
Labels: release

#32 #177 Configuração do ambiente de homologação
  .env.staging
  Dockerfile
  docker-compose.deploy.yml
Labels: devops

#27 #153 replace vue toasted
  package-lock.json
  package.json
  src/components/input/DatePicker.vue
  src/components/input/ImageUpload.vue
  src/components/input/Snackbar.vue
  src/components/input/StringList.vue
  src/components/layout/Card.vue
  src/components/layout/Upload.vue
  src/main.js
  src/plugins/axios.js
  src/plugins/vuelidate.js
  src/router.js
  src/store.js
  src/store/snackbar.js
  src/views/CalendarPage.vue
  src/views/HarvestRegistration.vue
  src/views/PropertyRegistration.vue
  src/views/Signin.vue
  src/views/Signup.vue
  src/views/TreeRegistration.vue
  tests/unit/signin.spec.js
Labels: attention, help wanted

#34 #178 Configuração do ambiente de produção do frontend
  .env.development
  .env.production
  .env.staging
  docker-compose.deploy.yml
  package.json
  server.js
  src/views/LandingPage.vue
Labels: devops

#38 #179 Deploy contínuo
  .github/workflows/cd.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  docker-compose.deploy.yml
  package.json
Labels: devops

#41 Release 3
  .env.development
  .env.production
  .env.staging
  .github/workflows/cd.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  Dockerfile
  docker-compose.deploy.yml
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  server.js
  src/components/input/DatePicker.vue
  src/components/input/ImageUpload.vue
  src/components/input/RegisterButton.vue
  src/components/input/SignButton.vue
  src/components/input/Snackbar.vue
  src/components/input/StringList.vue
  src/components/input/TextField.vue
  src/components/layout/Card.vue
  src/components/layout/HarvestCard.vue
  src/components/layout/ModalCard.vue
  src/components/layout/SideBar.vue
  src/components/layout/TopBar.vue
  src/components/layout/TreeCard.vue
  src/components/layout/Upload.vue
  src/components/visualization/HarvestDigest.vue
  src/components/visualization/PropertyDigest.vue
  src/main.js
  src/plugins/axios.js
  src/plugins/i18n.js
  src/plugins/vuelidate.js
  src/router.js
  src/store.js
  src/store/snackbar.js
  src/views/CalendarPage.vue
  src/views/Dashboard.vue
  src/views/HarvestRegistration.vue
  src/views/HarvestView.vue
  src/views/HomePage.vue
  src/views/LandingPage.vue
  src/views/Property.vue
  src/views/PropertyRegistration.vue
  src/views/Signin.vue
  src/views/Signup.vue
  src/views/TreeRegistration.vue
  src/views/UserUpdate.vue
  tests/unit/components.spec.js
  tests/unit/signin.spec.js
Labels: release
